version: "3.8"
services:
  capio:
    image: hpio/capio:latest
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - capionet
    volumes:
      - type: bind
        source: ./server
        target: /home/capio/server
networks:
  capionet:
