#!/usr/bin/env python3

import argparse
import json
import os
import signal
import socket
import subprocess
import sys
import time


###################
### Single Node ###
###################

### Single App Setup ###
# Location: node1
# Processes: capiorun1, server, app1
# Events:
#   - app1 completes execution
#   - capiorun1 sends SIGUSR1 to the server
#   - Server can terminate after handling the signal

### Multi-App Setup ###
# Location: node1
# Processes: capiorun1, capiorun2, server, app1, app2
# Events:
#   - app1 completes execution
#   - capiorun1 does NOT send SIGUSR1 to the server if app2 is still running
#   - app2 completes execution
#   - capiorun2 sends SIGUSR1 to the server, signaling completion


###################
### Multi-Node  ###
###################

### Single App on Each Node ###
# Node 1              Node 2
# Processes: capiorun1  capiorun2
#            server1    server2
#            app1       app2
# Events:
#   - app1 finishes execution
#   - app2 consumes app1's output
#   - server1 (Capio server) processes app2's request
#   - capiorun1 sends SIGUSR1 to server1
#   - server1 completes the request and terminates
#   - app2 finishes execution
#   - capiorun2 sends SIGUSR1 to server2, signaling completion


def build_env(args, workflow_name, is_server=False):
    env = os.environ.copy()
    if args.log_dir:
        env["CAPIO_LOG_DIR"] = args.log_dir
    if args.log_prefix:
        env["CAPIO_LOG_PREFIX"] = args.log_prefix
    if args.cache_lines:
        env["CAPIO_CACHE_LINES"] = args.cache_lines
    if args.init_file_size:
        env["CAPIO_FILE_INIT_SIZE"] = args.init_file_size
    env["CAPIO_DIR"] = args.capio_dir
    env["CAPIO_LOG_LEVEL"] = args.log_level
    env["CAPIO_WORKFLOW_NAME"] = workflow_name
    if is_server:
        env["CAPIO_METADATA_DIR"] = args.metadata_dir
    else:  # is a client
        env["CAPIO_APP_NAME"] = args.app_name
        env["LD_PRELOAD"] = args.libcapio
    return env


def count_files_starting_with(prefix):
    return sum(
        1
        for filename in os.listdir("/dev/shm")
        if os.path.isfile(os.path.join("/dev/shm", filename))
        and filename.startswith(prefix)
    )


def main(args):
    server_process = None
    step_process = None

    if args.capiocl != "--no-config":
        with open(args.capiocl, "r") as f:
            workflow_name = json.load(f)["name"]
    else:
        workflow_name = "CAPIO"

    if not os.path.exists(f"/dev/shm/{workflow_name}"):
        print(f"Starting capio server with config file: {args.capiocl}")
        print(f"CAPIO_APP_NAME      = {args.app_name}")
        print(f"CAPIO_DIR           = {args.capio_dir}")
        print(f"CAPIO_CL_CONFIG     = {args.capiocl}")
        print(f"CAPIO_LOG_DIR       = {args.log_dir}")
        print(f"CAPIO_LOG_LEVEL     = {args.log_level}")
        print(f"CAPIO_METADATA_DIR  = {args.metadata_dir}")
        print(f"CAPIO_WORKFLOW_NAME = {workflow_name}")
        if not os.path.exists(args.capiocl) and args.capiocl != "--no-config":
            print(f"File {args.capiocl} does not exists. aborting execution...")
            exit(1)
        server_env = build_env(args, workflow_name, is_server=True)

        hostname = socket.gethostname()
        pid = os.getpid()
        with open(
                os.path.join(args.log_dir, f"server_{hostname}_{pid}.out"), "w"
        ) as out_file:
            server_process = subprocess.Popen(
                [
                    args.server,
                    (
                        "--config " + args.capiocl
                        if args.capiocl != "--no-config"
                        else args.capiocl
                    ),
                ],
                env=server_env,
                cwd=args.log_dir,
                #stdout=out_file,
                #stderr=out_file,
                start_new_session=True,
            )

        print(f"{hostname} capiorun-pid {pid} - capio_server PID: {server_process.pid}")
        time.sleep(1)
    else:
        print(
            f"An instance of capio_server with workflow name {workflow_name} already exists!"
        )
    step_env = build_env(args, workflow_name)

    print(f"Starting workflow steps with following environment variables:")
    print(f"CAPIO_APP_NAME      = {args.app_name}")
    print(f"CAPIO_DIR           = {args.capio_dir}")
    print(f"CAPIO_LOG_LEVEL     = {args.log_level}")
    print(f"CAPIO_WORKFLOW_NAME = {workflow_name}")
    print(f"LD_PRELOAD          = {args.libcapio}")
    print(f"command             = {' '.join(args.args)}")
    try:
        step_process = subprocess.Popen(
            args.args,
            env=step_env,
            stdout=sys.stdout,
            stderr=sys.stderr,
        )
        step_process.wait()
        print(
            f"Step {args.app_name} terminated with returncode:", step_process.returncode
        )
    except Exception as e:
        print(
            f"An error occurred in startup/execution of workflow app <{args.app_name}>: {e}"
        )

    if server_process is not None:
        if count_files_starting_with(workflow_name) > 4:
            print(
                "Server instance is used by other applications... skipping server termination"
            )
        else:
            print(f"Terminating instance of capio_server")
            server_process.send_signal(signal.SIGUSR1)
            time.sleep(2)
            print("Terminated CAPIO server instance")
    else:
        if count_files_starting_with(workflow_name) <= 4:
            print(
                "Terminating instance of capio_server started by other capiorun command"
            )
            result = subprocess.run(
                ["killall", "-USR1", "capio_server"],
                stdout=sys.stdout,
                stderr=sys.stderr,
            )
            if result.returncode == 0:
                print("Terminated CAPIO server instance")
            else:
                print("Error terminating capio_server instance!")
        else:
            print("Skipping termination of capio_server")


def parse_args():
    parser = argparse.ArgumentParser(
        prog="capiorun",
        description="""
    capiorun - Simplified launcher for CAPIO-based applications.

    This utility streamlines the setup and execution of CAPIO workflows by automatically configuring
    the environment and managing capio_server instances. It allows running specific application steps
    defined in a CAPIO-CL configuration without manual setup of environment variables.

    Typical usage:
        capiorun -d /mnt/capio -n myapp -c config.json -- <app> <app options>
    """,
        epilog="""
    Developed by Marco Edoardo Santimaria <marcoedoardo.santimaria@unito.it>

    For more information, refer to the CAPIO documentation or repository.
    """,
        formatter_class=argparse.RawTextHelpFormatter,
    )

    # Required arguments
    parser.add_argument(
        "-d",
        "--capio-dir",
        required=True,
        help="CAPIO virtual mount point (e.g., /mnt/capio)",
    )
    parser.add_argument(
        "-n",
        "--app-name",
        required=True,
        help="Name of the CAPIO application step to launch. Must match an entry in the CAPIO-CL config.",
    )

    # Optional but commonly used
    parser.add_argument(
        "-c",
        "--capiocl",
        default="--no-config",
        help="Path to the CAPIO-CL configuration file (default: --no-config)",
    )
    parser.add_argument(
        "-m", "--metadata-dir", default="", help="Custom directory for metadata"
    )

    # Debug and logging
    parser.add_argument(
        "-L",
        "--log-level",
        default="-1",
        help="CAPIO log level. Useful when running in debug mode (default: -1)",
    )
    parser.add_argument(
        "--log-dir", default="", help="Custom directory for CAPIO log output"
    )
    parser.add_argument("--log-prefix", default="", help="Prefix for CAPIO log files")

    # Tuning and advanced
    parser.add_argument(
        "--cache-lines",
        default="",
        help="Number of CAPIO shm-queue cache lines (optional tuning parameter)",
    )
    parser.add_argument(
        "--init-file-size",
        default="",
        help="Default file size (in bytes) when pre-allocating memory for new files",
    )

    # Binary locations
    parser.add_argument(
        "-l",
        "--libcapio",
        default="libcapio_posix.so",
        help="Path to libcapio_posix.so shared library (default: libcapio_posix.so)",
    )
    parser.add_argument(
        "-s",
        "--server",
        default="capio_server",
        help="Path to capio_server executable (default: capio_server)",
    )

    # Positional arguments
    parser.add_argument(
        "args", nargs=argparse.REMAINDER, help="Command to launch with capio"
    )
    return parser.parse_args()


if __name__ == "__main__":
    main(parse_args())
