#!python3
from Importer import Importer
from parser import parse_json
import argparse
import generators.BashGenerator as bashGenerator

from loguru import logger

logger.remove()
logger.add(
    sink=lambda msg: print(msg, end=''),  # or use sys.stdout
    format="<green>{time:DD/MM/YYYY HH:mm:ss}</green> | <cyan>{name}</cyan> | <level>{level: <8}</level> | <level>{message}</level>",
    colorize=True
)

parser = argparse.ArgumentParser(prog='capiorun', description='Automate the execution of workflows running with CAPIO',
                                 epilog='Developed by Marco Edoardo Santimaria')

parser.add_argument("-w", "--workflow", default="capiorun.json", help="JSON file containing the workflow description")
parser.add_argument("--capio-cl", default="capiorun-cl.json", help="CAPIO-CL configuration file path")
parser.add_argument("--no-capio-cl", default=False, action="store_true", help="CAPIO-CL configuration file path")
parser.add_argument("--server", default="capio_server", help="CAPIO Server executable path")
parser.add_argument("--server-args", default="", help="CAPIO Server arguments (excluding CAPIO-CL configuration flags)")
parser.add_argument("--libcapio", default="libcapio_posix.so", help="CAPIO intercept library path")
parser.add_argument("--target", "-t", help="Kind of submission files to generate", default="bash")
parser.add_argument("--no-execute",
                    action="store_false",
                    default=True,
                    help="Generate only workflow scripts, but do not start it")

if __name__ == "__main__":

    args = parser.parse_args()
    if not args.workflow:
        logger.critical("No workflow provided")
        exit(-11)

    workflow = parse_json(args.workflow)
    CAPIO_DIR = workflow['capio-dir']
    logger.info(f"CAPIO_DIR={workflow['capio-dir']}")

    importer = Importer(steps=workflow['steps'], capio_dir=CAPIO_DIR, workflow_name=workflow['workflow-name'])

    jobs_to_submit = importer.import_steps()

    generator = None

    if "bash" in args.target:
        logger.info(f"Using BASH generator")
        generator = bashGenerator.BashGenerator(workflow)
    elif "slurm" in args.target:
        logger.info(f"Using SLURM generator")
    else:
        logger.critical("Error: requested generator does not exist")

    if generator is None:
        logger.critical("Error: requested generator is not instantiated")
        exit(-1)

    master_script_path = generator.generate(
        jobs_to_submit,
        capio_dir=CAPIO_DIR,
        server_path=args.server,
        server_args=args.server_args,
        server_config_path=("-c " + args.capio_cl),
        intercept_path=args.libcapio
    )
    logger.success(f"Generated submission scripts")

    if args.no_execute:
        generator.run()
