#ifndef CAPIO_POSIX_HANDLERS_HPP
#define CAPIO_POSIX_HANDLERS_HPP

#include "handlers/access.hpp"
#include "handlers/chdir.hpp"
#include "handlers/clone.hpp"
#include "handlers/close.hpp"
#include "handlers/creat.hpp"
#include "handlers/dup.hpp"
#include "handlers/execve.hpp"
#include "handlers/exit_group.hpp"
#include "handlers/faccessat.hpp"
#include "handlers/fchmod.hpp"
#include "handlers/fchown.hpp"
#include "handlers/fgetxattr.hpp"
#include "handlers/fcntl.hpp"
#include "handlers/fork.hpp"
#include "handlers/fstat.hpp"
#include "handlers/fstatat.hpp"
#include "handlers/fstatfs.hpp"
#include "handlers/getcwd.hpp"
#include "handlers/getdents.hpp"
#include "handlers/ioctl.hpp"
#include "handlers/lseek.hpp"
#include "handlers/lstat.hpp"
#include "handlers/mkdir.hpp"
#include "handlers/mkldirat.hpp"
#include "handlers/openat.hpp"
#include "handlers/read.hpp"
#include "handlers/rename.hpp"
#include "handlers/unlink.hpp"
#include "handlers/unlinkat.hpp"
#include "handlers/write.hpp"
#include "handlers/writev.hpp"

#endif // CAPIO_POSIX_HANDLERS_HPP
