services:

  download:
    env_file: .env
    image: hpio/capio:latest
    networks:
      - capionet
    volumes:
      - ${HOST_SRC_DIR}:${GUEST_TARGET_DIR}
    command: ${GUEST_TARGET_DIR}/download 1

  individuals:
    env_file: .env
    image: hpio/capio:latest
    networks:
      - capionet
    deploy:
      mode: replicated
      replicas: ${REPLICAS}
    volumes:
      - ${HOST_SRC_DIR}:${GUEST_TARGET_DIR}
    command: #${GUEST_TARGET_DIR}/individuals data/20130502/ALL.chr1.250000.vcf 1 1 2000 10000

  individuals-merge:
    env_file: .env
    image: hpio/capio:latest
    networks:
      - capionet
    volumes:
      - ${HOST_SRC_DIR}:${GUEST_TARGET_DIR}
    command: #${GUEST_TARGET_DIR}/individuals_merge 1 chr1n-1-2000.tar.gz

  sifting:
    env_file: .env
    image: hpio/capio:latest
    networks:
      - capionet
    volumes:
      - ${HOST_SRC_DIR}:${GUEST_TARGET_DIR}
    command: #${GUEST_TARGET_DIR}/sifting data/20130502/sifting/ALL.chr1.phase3_shapeit2_mvncall_integrated_v5.20130502.sites.annotation.vcf

  mutation-overlap:
    env_file: .env
    image: hpio/capio:latest
    networks:
      - capionet
    deploy:
      mode: replicated
      replicas: ${REPLICAS}
    volumes:
      - ${HOST_SRC_DIR}:${GUEST_TARGET_DIR}
    command: #${GUEST_TARGET_DIR}/mutation_overlap --c 1 --pop ALL 2> out.log > out.txt

  frequency:
    env_file: .env
    image: hpio/capio:latest
    networks:
      - capionet
    deploy:
      mode: replicated
      replicas: ${REPLICAS}
    volumes:
      - ${HOST_SRC_DIR}:${GUEST_TARGET_DIR}
    command: #${GUEST_TARGET_DIR}/frequency -c 1 -pop ALL

networks:
  capionet:

