#ifndef SOURCETEXT_HPP
#define SOURCETEXT_HPP

constexpr char SOURCE_TEST_TEXT[] =
    "Cantami, o Diva, del Pelìde Achille l'ira funesta che infiniti addusse lutti agli Achei, "
    "molte anzi tempo all'Orco generose travolse alme d'eroi, e di cani e d'augelli orrido pasto "
    "lor salme abbandonò (così di Giove l'alto consiglio s'adempìa), da quando primamente "
    "disgiunse aspra contesa il re de' prodi Atride e il divo Achille. E qual de' numi inimicolli? "
    "Il figlio di Latona e di Giove. Irato al Sire destò quel Dio nel campo un feral morbo, e la "
    "gente perìa: colpa d'Atride che fece a Crise sacerdote oltraggio. Degli Achivi era Crise alle "
    "veloci prore venuto a riscattar la figlia con molto prezzo. In man le bende avea, e l'aureo "
    "scettro dell'arciero Apollo: e agli Achei tutti supplicando, e in prima ai due supremi "
    "condottieri Atridi: O Atridi, ei disse, o coturnati Achei, gl'immortali del cielo abitatori "
    "concedanvi espugnar la Prïameia cittade, e salvi al patrio suol tornarvi. Deh mi sciogliete "
    "la diletta figlia, ricevetene il prezzo, e il saettante figlio di Giove rispettate. - Al "
    "prego tutti acclamâr: doversi il sacerdote riverire, e accettar le ricche offerte. Ma la "
    "proposta al cor d'Agamennóne non talentando, in guise aspre il superbo accommiatollo, e "
    "minaccioso aggiunse: Vecchio, non far che presso a queste navi ned or né poscia più ti colga "
    "io mai; ché forse nulla ti varrà lo scettro né l'infula del Dio. Franca non fia costei, se "
    "lungi dalla patria, in Argo, nella nostra magion pria non la sfiori vecchiezza, all'opra "
    "delle spole intenta, e a parte assunta del regal mio letto. Or va, né m'irritar, se salvo ir "
    "brami. Impaurissi il vecchio, ed al comando obbedì. Taciturno incamminossi del risonante mar "
    "lungo la riva; e in disparte venuto, al santo Apollo di Latona figliuol, fe' questo prego: "
    "Dio dall'arco d'argento, o tu che Crisa proteggi e l'alma Cilla, e sei di Tènedo possente "
    "imperador, Smintèo, deh m'odi. Se di serti devoti unqua il leggiadro tuo delubro adornai, se "
    "di giovenchi e di caprette io t'arsi i fianchi opimi, questo voto m'adempi; il pianto mio "
    "paghino i Greci per le tue saette. Sì disse orando. L'udì Febo, e scese dalle cime d'Olimpo "
    "in gran disdegno coll'arco su le spalle, e la faretra tutta chiusa. Mettean le frecce orrendo "
    "su gli omeri all'irato un tintinnìo al mutar de' gran passi; ed ei simìle a fosca notte giù "
    "venìa. Piantossi delle navi al cospetto: indi uno strale liberò dalla corda, ed un ronzìo "
    "terribile mandò l'arco d'argento. Prima i giumenti e i presti veltri assalse, poi le schiere "
    "a ferir prese, vibrando le mortifere punte; onde per tutto degli esanimi corpi ardean le "
    "pire. Nove giorni volâr pel campo acheo le divine quadrella. A parlamento nel decimo chiamò "
    "le turbe Achille; ché gli pose nel cor questo consiglio Giuno la diva dalle bianche braccia, "
    "de' moribondi Achei fatta pietosa. Come fur giunti e in un raccolti, in mezzo levossi Achille "
    "piè-veloce, e disse: Atride, or sì cred'io volta daremo nuovamente errabondi al patrio lido, "
    "se pur morte fuggir ne fia concesso; ché guerra e peste ad un medesmo tempo ne struggono. Ma "
    "via; qualche indovino interroghiamo, o sacerdote, o pure interprete di sogni (ché da Giove "
    "anche il sogno procede), onde ne dica perché tanta con noi d'Apollo è l'ira: se di preci o di "
    "vittime neglette il Dio n'incolpa, e se d'agnelli e scelte capre accettando l'odoroso fumo, "
    "il crudel morbo allontanar gli piaccia. Così detto, s'assise. In piedi allora di Testore il "
    "figliuol Calcante alzossi, de' veggenti il più saggio, a cui le cose eran conte che fur, sono "
    "e saranno; e per quella, che dono era d'Apollo, profetica virtù, de' Greci a Troia avea "
    "scorte le navi. Ei dunque in mezzo pien di senno parlò queste parole: Amor di Giove, generoso "
    "Achille, vuoi tu che dell'arcier sovrano Apollo ti riveli lo sdegno? Io t'obbedisco. Ma del "
    "braccio l'aita e della voce a me tu pria, signor, prometti e giura: perché tal che qui grande "
    "ha su gli Argivi tutti possanza, e a cui l'Acheo s'inchina, n'andrà, per mio pensar, molto "
    "sdegnoso. Quando il potente col minor s'adira, reprime ei sì del suo rancor la vampa per "
    "alcun tempo, ma nel cor la cova, finché prorompa alla vendetta. Or dinne se salvo mi farai. - "
    "Parla securo, rispose Achille, e del tuo cor l'arcano, qual ch'ei si sia, di' franco. Per "
    "Apollo che pregato da te ti squarcia il velo de' fati, e aperto tu li mostri a noi, per "
    "questo Apollo a Giove caro io giuro: nessun, finch'io m'avrò spirto e pupilla, con empia mano "
    "innanzi a queste navi oserà vïolar la tua persona, nessuno degli Achei; no, s'anco parli "
    "d'Agamennón che sé medesmo or vanta dell'esercito tutto il più possente. Allor fe' core il "
    "buon profeta, e disse: né d'obblïati sacrifici il Dio né di voti si duol, ma dell'oltraggio "
    "che al sacerdote fe' poc'anzi Atride, che francargli la figlia ed accettarne il riscatto "
    "negò. La colpa è questa onde cotante ne diè strette, ed altre l'arcier divino ne darà; né "
    "pria ritrarrà dal castigo la man grave, che si rimandi la fatal donzella non redenta né "
    "compra al padre amato, e si spedisca un'ecatombe a Crisa. Così forse avverrà che il Dio si "
    "plachi. Tacque, e s'assise. Allor l'Atride eroe il re supremo Agamennón levossi corruccioso. "
    "Offuscavagli la grande ira il cor gonfio, e come bragia rossi fiammeggiavano gli occhi. E "
    "tale ei prima squadrò torvo Calcante, indi proruppe: Profeta di sciagure, unqua un accento "
    "non uscì di tua bocca a me gradito. Al maligno tuo cor sempre fu dolce predir disastri, e "
    "d'onor vote e nude son l'opre tue del par che le parole. E fra gli Argivi profetando or "
    "cianci che delle frecce sue Febo gl'impiaga, sol perch'io ricusai della fanciulla Crisëide il "
    "riscatto. Ed io bramava certo tenerla in signoria, tal sendo che a Clitennestra pur, da me "
    "condutta vergine sposa, io la prepongo, a cui di persona costei punto non cede, né di care "
    "sembianze, né d'ingegno ne' bei lavori di Minerva istrutto. Ma libera sia pur, se questo è il "
    "meglio; ché la salvezza io cerco, e non la morte del popol mio. Ma voi mi preparate tosto il "
    "compenso, ché de' Greci io solo restarmi senza guiderdon non deggio; ed ingiusto ciò fôra, or "
    "che una tanta preda, il vedete, dalle man mi fugge. O d'avarizia al par che di grandezza "
    "famoso Atride, gli rispose Achille, qual premio ti daranno, e per che modo i magnanimi Achei? "
    "Che molta in serbo vi sia ricchezza non partita, ignoro: delle vinte città tutte divise ne "
    "fur le spoglie, né diritto or torna a nuove parti congregarle in una.";

#endif // SOURCETEXT_HPP
